version: '3.8'

services:
  hvac-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEVICE=auto
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      "uvicorn app.main:app --host 0.0.0.0 --port 8000"